name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14.19.0
        uses: actions/setup-node@v2
        with:
          node-version: "14.19.0"
      - name: Install dependencies
        run: npm install
      - name: Printing angular version
        run: npm run ng version
      - name: Build
        run: npm run build:ssr
      - name: Deploy to external repository
        uses: "cpina/github-action-push-to-another-repository@main"
        env:
          API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}}
        with:
          source-directory: dist/
          destination-github-username: "MukundDholariya2706"
          destination-repository-name: "angular-material-build"
          user-email: "mukunddtridhyatech@gmail.com"
          target-branch: "main"
      - name: Send Email on Success
        if: success()
        run: |
          echo "Subject: Workflow Succeeded" > email.txt
          echo "Your Workflow has succeeded!" >> email.txt
          cat email.txt | mail -s "$(cat email.txt | head -n 1)" mukunddtridhyatech@gmail.com
        env:
          MAILTO: mukunddtridhyatech@gmail.com
      - name: Send Email on Failure
        if: failure()
        run: |
          echo "Subject: Workflow Failed" > email.txt
          echo "Your workflow has failed! Please check the GitHub Actions logs for details." >> email.txt
          cat email.txt | mail -s "$(cat email.txt | head -n 1)" mukunddtridhyatech@gmail.com
        env:
          MAILTO: mukunddtridhyatech@gmail.com
